Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -87,13 +87,16 @@ jobs:
       working-directory: ./MLProject
       shell: bash -l {0}
       run: |
-        mlflow artifacts download -r ${{ env.LATEST_RUN_ID }} --dst-path ./artifacts
+        if ! mlflow artifacts download --run-id ${{ env.LATEST_RUN_ID }} --artifact-path ./artifacts --dst-path ./artifacts; then
+            echo "Failed to download artifacts. Exiting."
+            exit 1
+        fi
         cat ./artifacts/metrics.json
         METRIC=$(jq '.accuracy' ./artifacts/metrics.json)
         echo "Model Accuracy: $METRIC"
         if (( $(echo "$METRIC < 0.85" | bc -l) )); then
-          echo "Model accuracy is too low. Failing pipeline."
-          exit 1
+            echo "Model accuracy is too low. Failing pipeline."
+            exit 1
         fi
 
     - name: Prepare Artifacts
